if(OS_MACOS)
  add_library(libcurl INTERFACE)
  target_include_directories(libcurl SYSTEM INTERFACE /usr/local/opt/curl/include)
  target_link_libraries(libcurl INTERFACE /usr/local/opt/curl/lib/libcurl.a)
else()
  if(OS_WINDOWS)
    set(CURL_USE_OPENSSL OFF)
    set(CURL_USE_SCHANNEL ON)
  elseif(OS_LINUX)
    add_compile_options(-fPIC)
    set(CURL_USE_OPENSSL ON)
  endif()
  set(BUILD_CURL_EXE OFF)
  set(BUILD_SHARED_LIBS OFF)
  set(HTTP_ONLY OFF)
  set(CURL_USE_LIBSSH2 OFF)
  set(CURL_DISABLE_FTP ON)
  set(CURL_DISABLE_LDAP ON)
  set(CURL_DISABLE_LDAPS ON)
  set(CURL_DISABLE_TELNET ON)
  set(CURL_DISABLE_MQTT ON)
  set(CURL_DISABLE_POP3 ON)
  set(CURL_DISABLE_RTMP ON)
  set(CURL_DISABLE_SMTP ON)
  set(CURL_DISABLE_GOPHER ON)

  add_subdirectory(vendor/curl EXCLUDE_FROM_ALL)
  include_directories(SYSTEM ${CMAKE_SOURCE_DIR}/vendor/curl/include)
endif()
